source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target "CODataImport" do
  pod 'MagicalRecord', :git => 'https://github.com/phucdanghuu/MagicalRecord.git', :branch => 'master'
end

# Post-install hook to force iOS 12.0 for dependencies
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
