source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target "CODataImport" do
  pod 'MagicalRecord', '~> 2.3.2'
end

target "CODataImportUnitTest" do
  pod 'MagicalRecord', '~> 2.3.2'
end
