source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target "CODataImport" do
  pod 'MagicalRecord', '~> 2.3.2'
end

target "CODataImportUnitTest" do
  pod 'MagicalRecord', '~> 2.3.2'
end

#post_install do |installer|
#  installer.pods_project.build_configurations.each do |config|
#    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#  end
#end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
